---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: honda-lde-webapp-bootstrap
spec:
  destination:
    namespace: honda-labs-ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: honda-lde-webapp
      valueFiles:
      - ci-cd-values.yaml
    path: charts/honda-lde-webapp
    repoURL: https://github.com/honda-lde/open-suite-webapp.git
    targetRevision: pipelines 
