{{- if .Values.builds }}
{{- range .Values.builds }}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "{{ .name}}"
  namespace: {{ .namespace | default $.Values.namespace | quote }}
spec:
  nodeSelector: {}
  runPolicy: {{ .run_policy | default "Serial" | quote }}
  triggers:
    - type: "{{ .trigger_type }}"
      {{ .trigger_type | lower }}:
        secret: "{{ .secret_name }}"
    - type: "ImageChange"
  source:
    contextDir: {{ .source_context_dir | default "" | quote }}
    git:
      uri: "{{ .source_repo }}"
      ref: {{ .source_repo_ref | default "master" | quote }}
    sourceSecret:
      name: "{{ .secret_name }}"
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "{{ .builder_image_name }}:{{ .builder_image_tag }}"
        namespace: {{ .builder_image_namespace | default "openshift" | quote }}
  output:
    to:
      kind: "ImageStreamTag"
      name: "{{ .name }}:latest"
status:
  lastVersion: 0
{{- end }}
{{- end }}

