{{- if .Values.deploymentconfigs }}
{{- range $dc := .Values.deploymentconfigs }}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ $dc.name }}
  namespace: {{ $dc.namespace | default $.Values.namespace | quote }}
spec:
  replicas: {{ $dc.replicas | default "1" }}
  selector:
    deploymentConfig: "{{ $dc.name }}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentConfig: "{{ $dc.name }}"
      name: "{{ $dc.name }}"
    spec:
      containers:
      - env:
{{ toYaml $dc.env_vars | indent 8 }}
        image: "{{ $dc.image_name | default $dc.name }}:{{ $dc.image_version }}"
        imagePullPolicy: Always
        name: "{{ $dc.name }}"
        ports:
{{- range $ports := $dc.ports }}
          - name: {{ $ports.name }}
            containerPort: {{ $ports.containerPort }}
            protocol: {{ $ports.protocol }}
{{- end }}
{{- if $dc.volume_mounts }}
        volumeMounts:
{{ toYaml $dc.volume_mounts | indent 8 }}
{{- end }}
{{- if $dc.volumes }}
      volumes:
{{ toYaml $dc.volumes | indent 6 }}
{{- end }}
      terminationGracePeriodSeconds: 60
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ $dc.name }}"
      from:
        kind: ImageStreamTag
        name: "{{ $dc.image_name | default $.Values.app_name }}:{{ $dc.image_version }}"
    type: ImageChange
  - type: ConfigChange
{{- end }}
{{- end }}
