{{- if .Values.imagestreams }}
{{- range .Values.imagestreams }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ $.Values.app_name }}" 
  namespace: "{{ .namespace }}"
spec: {}
{{- end }}
{{- end }}
