{{- if .Values.imagestreams }}
{{- range .Values.imagestreams }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ .name }}"
  namespace: {{ .namespace | default $.Values.namespace | quote }}
spec: {}
{{- end }}
{{- end }}

