 # Declare variables to be passed into your templates.


deploymentconfigs:
  - namespace: honda-dev
    name: honda-lde-webapp
    replicas: 1
    env_vars:
      - name: "DB_NAME"
        valueFrom:
         secretKeyRef:
           name: honda-lde-webapp-creds
           key: database-name
      - name: "DB_USER"
        valueFrom:
          secretKeyRef:
            name: "honda-lde-webapp-creds"
            key: database-user
      - name: "DB_PASS"
        valueFrom:
          secretKeyRef:
            name: "honda-lde-webapp-creds"
            key: database-password
      - name: DB_SERVICE_NAME
        value: "honda-lde-webapp-db"
    ports:
        - containerPort: 8080
          name: http
          protocol: TCP
    image_version: "latest"
  - namespace: honda-dev
    name: axelor-service-db
    replicas: 1
    env_vars:
      - name: PGCTLTIMEOUT
        value: "300"
      - name: POSTGRESQL_USER
        valueFrom:
          secretKeyRef:
            name: honda-lde-webapp-creds
            key: database-user
      - name: POSTGRESQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: honda-lde-webapp-creds
            key: database-password
      - name: POSTGRESQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: honda-lde-webapp-creds
            key: database-name
    ports:
      - containerPort: 5432
        protocol: TCP
        name: pg
    image: "postgresql"
    image_version: "10"